export enum ItemActionTypes {
  GET_ITEMS = 'GET_ITEMS',
  GET_ITEM = 'GET_ITEM',
  ADD_ITEM = 'ADD_ITEM',
  EDIT_ITEM = 'EDIT_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
  ITEMS_LOADING = 'ITEMS_LOADING',
  ITEMS_ERROR = 'ITEMS_ERROR',
}
